---
sidebar: sidebar
permalink: concept-install-options-google.html
keywords: install connector google cloud, google cloud install connector, connector google cloud, google cloud connector, install connector gcp, gcp install connector, connector gcp, gcp connector, installation options, manual install
summary: There are a few different ways to create a Connector in Google Cloud. Directly from BlueXP is the most common way.
---

= Connector installation options in Google Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are a few different ways to create a Connector in Google Cloud. Directly from BlueXP is the most common way.

The following installation options are available:

* Create the Connector directly from BlueXP (this is the standard option)
+
This action launches a VM instance running Linux and the Connector software in a VPC of your choice.

* Create the Connector using gcloud
+
This action also launches a VM instance running Linux and the Connector software.

* Download and manually install the software on your own Linux host

The installation option that you choose impacts how you prepare for installation. This includes how you provide BlueXP with the required permissions that it needs to authenticate and manage resources in Google Cloud.

link:task-install-connector-google.html[Learn how to install the Connector in Google Cloud].