---
sidebar: sidebar
permalink: concept-install-options-azure.html
keywords: aws networking, networking, connector networking, ports, proxy server, outbound internet, endpoints, urls, permissions, cloud permission, aws permissions, iam role, keys, aws keys, aws marketplace, marketplace install, manuall install, connector installer
summary: Deploy a Connector in AWS so that BlueXP can manage resources and processes within your public cloud environment.
---

= Connecotor installation options in Azure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are a few different ways to create a Connector in Azure. Directly from BlueXP is the most common way.

The following options are available:

* Create the Connector directly from BlueXP (this is the standard option)
+
This action launches a VM running Linux and the Connector software in a VNet of your choice.

* Create a Connector from the Azure Marketplace
+
This action also launches a VM running Linux and the Connector software.

* Download and manually install the software on your own Linux host

The installation option that you choose impacts how you prepare for installation. This includes how you provide BlueXP with the required permissions that it needs to authenticate and manage resources in Azure.