---
sidebar: sidebar
permalink: concept-overview.html
keywords: overview, concepts, features, use case, cloud manager
summary: BlueXP enables IT experts and cloud architects to centrally manage their hybrid multi-cloud infrastructure using NetApp's cloud solutions.
---

= Learn about BlueXP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP enables IT experts and cloud architects to centrally manage their hybrid multi-cloud infrastructure using NetApp's cloud solutions.

== Features

BlueXP is an enterprise-class, SaaS-based management platform that keeps you in control of your data no matter where it is.

* Set up and use https://cloud.netapp.com/ontap-cloud[Cloud Volumes ONTAP^] for efficient, multi-protocol data management across clouds.
* Set up and use cloud file-storage services:
+
** https://bluexp.netapp.com/azure-netapp-files[Azure NetApp Files^]
** https://bluexp.netapp.com/fsx-for-ontap[Amazon FSx for ONTAP^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp[Cloud Volumes Service for Google Cloud^]
* Discover and manage https://bluexp.netapp.com/netapp-on-premises[on-premises storage^]
** E-Series systems
** ONTAP clusters
** StorageGRID systems
* Use BlueXP's services for data mobility, data protection, and data analysis and control:
** https://bluexp.netapp.com/cloud-backup[Cloud Backup^]
** https://bluexp.netapp.com/netapp-cloud-data-sense[Cloud Data Sense^]
** https://bluexp.netapp.com/cloud-sync-service[Cloud Sync^]
** https://bluexp.netapp.com/cloud-tiering[Cloud Tiering^]
** https://bluexp.netapp.com/digital-advisor[Digital Advisor^]
** https://bluexp.netapp.com/global-file-cache[Global File Cache^]
** https://bluexp.netapp.com/k8s[Kubernetes^]
** https://bluexp.netapp.com/ransomware-protection[Ransomware Protection^]
** https://bluexp.netapp.com/replication[Replication^]

https://cloud.netapp.com/cloud-manager[Learn more about BlueXP^]

== Supported cloud providers

BlueXP enables you to manage cloud storage and use cloud services in Amazon Web Services, Microsoft Azure, and Google Cloud.

== Cost

Pricing for BlueXP depends on the services that you plan to use. https://bluexp.netapp.com/pricing[Learn about BlueXP pricing^]

== How BlueXP works

BlueXP includes a SaaS-based interface that is integrated with the BlueXP website and Connectors that manage Cloud Volumes ONTAP and other cloud services.

=== Software-as-a-service

BlueXP is accessible through a https://console.bluexp.netapp.com[SaaS-based user interface^] and APIs. This SaaS experience enables you to automatically access the latest features as they're released and to easily switch between your NetApp accounts and Connectors.

=== Restricted and private sites

BlueXP is also supported in environments where you need to restrict some or all internet access. In those environments, you access the BlueXP interface and API through the Connector software, rather than through the SaaS website.

link:concept-modes.html[Learn about BlueXP deployment modes].

=== BlueXP website

https://cloud.netapp.com[The BlueXP website^] provides a centralized location to access and manage https://www.netapp.com/us/products/cloud-services/use-cases-for-netapp-cloud-services.aspx[NetApp cloud services^]. With centralized user authentication, you can use the same set of credentials to access BlueXP and other cloud services like Cloud Insights.

=== NetApp account

When you log in to BlueXP for the first time, you're prompted to create a _NetApp account_. This account provides multi-tenancy and enables you to organize users and resources in isolated _workspaces_.

=== Connectors

In most cases, a BlueXP Account Admin will need to deploy a _Connector_ in your cloud or on-premises network. The Connector enables BlueXP to manage resources and processes within your hybrid cloud environment.

In the case of restricted mode and private mode, the Connector also includes the interface that you use to interact with BlueXP.

link:concept-connectors.html[Learn more about when Connectors are required and how they work].

== SOC 2 Type 2 certification

An independent certified public accountant firm and services auditor examined BlueXP, Cloud Sync, Cloud Tiering, Cloud Data Sense, and Cloud Backup (BlueXP platform), and affirmed that they have achieved SOC 2 Type 2 reports based on the applicable Trust Services criteria.

https://www.netapp.com/company/trust-center/compliance/soc-2/[View NetApp's SOC 2 reports^]
