---
sidebar: sidebar
permalink: concept-connectors.html
keywords: concept, connectors, learn about connectors, service connectors, what are connectors, what is a connector, what's a connector, days, 14 days
summary: In most cases, you will need to deploy a Connector in your cloud or on-premises network. The Connector is a crucial component for the day-to-day use of BlueXP. It enables BlueXP to manage the resources and processes within your public cloud environment.
---

= Learn about Connectors
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
In most cases, a BlueXP Account Admin will need to deploy a _Connector_ in your cloud or on-premises network. The Connector is a crucial component for the day-to-day use of BlueXP. It enables BlueXP to manage the resources and processes within your public cloud environment.

== When a Connector is required

When you use BlueXP in standard mode through the SaaS website, a Connector is required for the following features and services in BlueXP:

* Amazon FSx for ONTAP management features
* Amazon S3 discovery
* Azure Blob discovery
* Cloud Backup
* Cloud Data Sense
* Cloud Tiering
* Cloud Volumes ONTAP
* E-Series systems
* Global File Cache
* Google Cloud Storage discovery
* Kubernetes clusters
* On-premises ONTAP cluster integration with BlueXP data services
* StorageGRID

A Connector is *_not_* required for the following services:

* Digital Advisor
+
In almost all cases, you can add a license to the Digital Wallet without a Connector.
+
The only time that a Connector is required to add a license to the Digital Wallet is for Cloud Volumes ONTAP _node-based_ licenses. A Connector is required in this case because the data is taken from the licenses installed on Cloud Volumes ONTAP systems.

* Amazon FSx for ONTAP working environment creation
+
While a Connector isn't required to create a working environment, it is required to create and manage volumes, replicate data, and integrate FSx for ONTAP with NetApp cloud services, such as Data Sense and Cloud Sync.

* Azure NetApp Files
+
While a Connector isn't required to set up and manage Azure NetApp Files, a Connector is required if you want to use Cloud Data Sense to scan Azure NetApp Files data.

* Cloud Volumes Service for Google Cloud

* Cloud Sync

* Direct discovery of on-premises ONTAP clusters
+
While a Connector isn't required for direct discovery of an on-premises ONTAP cluster, a Connector is required if you want to take advantage of additional BlueXP features. 
+
https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html[Learn more about discovery and management options for on-prem ONTAP clusters^]

== Supported locations

A Connector is supported in the following locations:

* Amazon Web Services

* Microsoft Azure
+
A Connector in Azure should be deployed in the same Azure region as the Cloud Volumes ONTAP systems that it manages, or in the https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies[Azure region pair^] for the Cloud Volumes ONTAP systems. This requirement ensures that an Azure Private Link connection is used between Cloud Volumes ONTAP and its associated storage accounts. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-enabling-private-link.html[Learn how Cloud Volumes ONTAP uses an Azure Private Link^]

* Google Cloud
+
If you want to use BlueXP services with Google Cloud, then you must use a Connector that's running in Google Cloud.

* On your premises

== Restricted mode and private mode

To use BlueXP in restricted mode or private mode, you get started with BlueXP by installing the Connector and then accessing the user interface or API that's running locally on the Connector.

link:concept-modes.html[Learn about BlueXP deployment modes].

== Connectors should remain running

A Connector should remain running at all times. It's important for the continued health and operation of the services that you enable.

For example, a Connector is a key component in the health and operation of Cloud Volumes ONTAP. If a Connector is powered down, Cloud Volumes ONTAP PAYGO systems and capacity-based BYOL systems shut down after losing communication with a Connector for longer than 14 days. This happens because the Connector refreshes licensing on the system each day.

NOTE: If your Cloud Volumes ONTAP system has a node-based BYOL license, the system remains running after 14 days because the license is installed on the Cloud Volumes ONTAP system.

BlueXP will notify you if your Connector has been powered down for 14 days or longer. https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-monitor-cm-operations.html[Learn about BlueXP notifications].

== How to create a Connector

A BlueXP Account Admin can create a Connector directly from BlueXP, from your cloud provider's marketplace, or by manually installing the software on your own Linux host. How you get started depends on whether you're using BlueXP in standard mode, restricted mode, or private mode.

* link:task-quick-start-standard-mode.html[Quick start for BlueXP in standard mode]
* link:task-quick-start-restricted-mode.html[Quick start for BlueXP in restricted mode]
* link:task-quick-start-private-mode.html[Quick start for BlueXP in private mode]

== Permissions

Specific permissions are needed to create the Connector directly from BlueXP and another set of permissions are needed for the Connector instance itself. If you create the Connector in AWS or Azure directly from BlueXP, then BlueXP creates the Connector with the permissions that it needs. There's nothing else that you need to do.

=== Permissions to create a Connector from BlueXP

The standard way to create a Connector is directly from BlueXP. Before you can do this, you need to set up permissions so that BlueXP can deploy the instance in your cloud provider of choice.

* link:task-creating-connectors-aws.html[View the required AWS permissions]
* link:task-set-up-permissions-azure.html#set-up-permissions-to-create-the-connector-from-bluexp[View the required Azure permissions]
* link:task-creating-connectors-gcp.html[View the required Google Cloud permissions]

=== Permissions for the Connector instance

The Connector needs specific cloud provider permissions to perform operations on your behalf. For example, to deploy and manage Cloud Volumes ONTAP.

When you create a Connector directly from BlueXP, BlueXP creates the Connector with the permissions that it needs. There's nothing that you need to do.

If you create the Connector from the AWS Marketplace, from the Azure Marketplace, or by manually installing the software, then you'll need to make sure that the right permissions are in place.

* link:reference-permissions-aws.html[Learn how the Connector uses AWS permissions]
* link:reference-permissions-azure.html[Learn how the Connector uses Azure permissions]
* link:reference-permissions-gcp.html[Learn how the Connector uses Google Cloud permissions]

== Connector upgrades

We typically update the Connector software each month to introduce new features and to provide stability improvements. While most of the services and features in the BlueXP platform are offered through SaaS-based software, a few features and functionalities are dependent on the version of the Connector. That includes Cloud Volumes ONTAP management, on-prem ONTAP cluster management, settings, and help.

The Connector automatically updates its software to the latest version, as long as it has outbound internet access to obtain the software update. If you're using BlueXP in private mode, then you'll need to manually upgrade the Connector.

== Number of working environments per Connector

A Connector can manage multiple working environments in BlueXP. The maximum number of working environments that a single Connector should manage varies. It depends on the type of working environments, the number of volumes, the amount of capacity being managed, and the number of users.

If you have a large-scale deployment, work with your NetApp representative to size your environment. If you experience any issues along the way, reach out to us by using the in-product chat.

== Multiple Connectors

In some cases, you might only need one Connector, but you might find yourself needing two or more Connectors.

Here are a few examples:

* You're using a multi-cloud environment (AWS and Azure), so you have one Connector in AWS and another in Azure. Each manages the Cloud Volumes ONTAP systems running in those environments.

* A service provider might use one BlueXP account to provide services for their customers, while using another account to provide disaster recovery for one of their business units. Each account would have separate Connectors.

=== When to switch between Connectors

When you create your first Connector, BlueXP automatically uses that Connector for each additional working environment that you create. Once you create an additional Connector, you'll need to switch between them to see the working environments that are specific to each Connector.

link:task-managing-connectors.html[Learn how to switch between Connectors].

=== Multiple Connectors with the same working environment

You can manage a working environment with multiple Connectors at the same time for disaster recovery purposes. If one Connector goes down, you can switch to the other Connector to immediately manage the working environment.

To set up this configuration:

. link:task-managing-connectors.html[Switch to another Connector]
. Discover the existing working environment.
+
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-adding-systems.html[Add existing Cloud Volumes ONTAP systems to BlueXP^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html[Discover ONTAP clusters^]
. Set the https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-storage-management.html[Capacity Management Mode^]
+
Only the main Connector should be set to *Automatic Mode*. If you switch to another Connector for DR purposes, then you can change the Capacity Management Mode as needed.