---
sidebar: sidebar
permalink: concept-connectors.html
keywords: concept, connectors, learn about connectors, service connectors, what are connectors, what is a connector, what's a connector, days, 14 days
summary: In most cases, you will need to deploy a Connector in your cloud or on-premises network. The Connector is a crucial component for the day-to-day use of BlueXP. It enables BlueXP to manage the resources and processes within your public cloud environment.
---

= Learn about Connectors
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
In most cases, a BlueXP Account Admin will need to deploy a _Connector_ in your cloud or on-premises network. The Connector is a crucial component for the day-to-day use of BlueXP. It enables BlueXP to manage the resources and processes within your public cloud environment.

== When a Connector is required

A Connector is required for the following features and services in BlueXP:

* Amazon FSx for ONTAP management features
* Amazon S3 discovery
* Azure Blob discovery
* Cloud Backup
* Cloud Data Sense
* Cloud Tiering
* Cloud Volumes ONTAP
* E-Series systems
* Global File Cache
* Google Cloud Storage discovery
* Kubernetes clusters
* On-premises ONTAP cluster integration with BlueXP data services
* StorageGRID

A Connector is *_not_* required for the following services:

* Digital Advisor
+
In almost all cases, you can add a license to the Digital Wallet without a Connector.
+
The only time that a Connector is required to add a license to the Digital Wallet is for Cloud Volumes ONTAP _node-based_ licenses. A Connector is required in this case because the data is taken from the licenses installed on Cloud Volumes ONTAP systems.

* Amazon FSx for ONTAP working environment creation
+
While a Connector isn't required to create a working environment, it is required to create and manage volumes, replicate data, and integrate FSx for ONTAP with NetApp cloud services, such as Data Sense and Cloud Sync.

* Azure NetApp Files
+
While a Connector isn't required to set up and manage Azure NetApp Files, a Connector is required if you want to use Cloud Data Sense to scan Azure NetApp Files data.

* Cloud Volumes Service for Google Cloud

* Cloud Sync

* Direct discovery of on-premises ONTAP clusters
+
While a Connector isn't required for direct discovery of an on-premises ONTAP cluster, a Connector is required if you want to take advantage of additional BlueXP features. 
+
https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html[Learn more about discovery and management options for on-prem ONTAP clusters^]

== Connectors must be operational at all times

Connectors are a fundamental part of the NetApp BlueXP service architecture. It is your responsibility to ensure that relevant Connectors are up, operational, and accessible at all times. While the service is designed to overcome short outages of Connector availability, you must take immediate action when required to remedy infrastructure failures.

This documentation is governed by the EULA. If the product is not operated in accordance with the documentation, the functionality and operation of the product, as well as your rights under the EULA, may be adversely impacted.

=== How Connector availability affects Cloud Volumes ONTAP

A Connector is a key component in the health and operation of Cloud Volumes ONTAP. If a Connector is powered down, Cloud Volumes ONTAP PAYGO systems and capacity-based BYOL systems shut down after losing communication with a Connector for longer than 14 days. This happens because the Connector refreshes licensing on the system each day.

NOTE: If your Cloud Volumes ONTAP system has a node-based BYOL license, the system remains running after 14 days because the license is installed on the Cloud Volumes ONTAP system.

== Supported locations

A Connector is supported in the following locations:

* Amazon Web Services
* Microsoft Azure
* Google Cloud
* On your premises
* On your premises, without internet access

=== Note about Azure deployments

If you deploy the Connector in Azure, it should be deployed in the same Azure region as the Cloud Volumes ONTAP systems that it manages, or in the https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies[Azure region pair^] for the Cloud Volumes ONTAP systems. This requirement ensures that an Azure Private Link connection is used between Cloud Volumes ONTAP and its associated storage accounts. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-enabling-private-link.html[Learn how Cloud Volumes ONTAP uses an Azure Private Link^].

=== Note about Google Cloud deployments

If you want to create a Cloud Volumes ONTAP system in Google Cloud, then you must have a Connector that's running in Google Cloud as well. You can't use a Connector that's running in AWS, Azure, or on-prem.

== How to create a Connector

A BlueXP Account Admin can create a Connector in a number of ways:

* Directly from BlueXP (recommended)
** link:task-creating-connectors-aws.html[Create in AWS]
** link:task-creating-connectors-azure.html[Create in Azure]
** link:task-creating-connectors-gcp.html[Create in GCP]
* By manually installing the software on your own Linux host
** link:task-installing-linux.html[On a host that has internet access]
** link:task-install-connector-onprem-no-internet.html[On a host in a location that doesn't have internet access]
* From your cloud provider's marketplace
** link:task-launching-aws-mktp.html[AWS Marketplace]
** link:task-launching-azure-mktp.html[Azure Marketplace]

If you are operating in a Government region, you need to deploy a Connector from your cloud provider's marketplace or by manually installing the Connector software on an existing Linux host. You can't deploy the Connector in a Government region from BlueXP's SaaS website.

== Permissions

Specific permissions are needed to create the Connector and another set of permissions are needed for the Connector instance itself.

=== Permissions to create a Connector

The user who creates a Connector from BlueXP needs specific permissions to deploy the instance in your cloud provider of choice.

* link:task-creating-connectors-aws.html[View the required AWS permissions]
* link:task-creating-connectors-azure.html[View the required Azure permissions]
* link:task-creating-connectors-gcp.html[View the required Google Cloud permissions]

=== Permissions for the Connector instance

The Connector needs specific cloud provider permissions to perform operations on your behalf. For example, to deploy and manage Cloud Volumes ONTAP.

When you create a Connector directly from BlueXP, BlueXP creates the Connector with the permissions that it needs. There's nothing that you need to do.

If you create the Connector yourself from the AWS Marketplace, the Azure Marketplace, or by manually installing the software, then you'll need to make sure that the right permissions are in place.

* link:reference-permissions-aws.html[Learn how the Connector uses AWS permissions]
* link:reference-permissions-azure.html[Learn how the Connector uses Azure permissions]
* link:reference-permissions-gcp.html[Learn how the Connector uses Google Cloud permissions]

== Connector upgrades

We typically update the Connector software each month to introduce new features and to provide stability improvements. While most of the services and features in the BlueXP platform are offered through SaaS-based software, a few features and functionalities are dependent on the version of the Connector. That includes Cloud Volumes ONTAP management, on-prem ONTAP cluster management, settings, and help.

The Connector automatically updates its software to the latest version, as long as it has outbound internet access to obtain the software update.

== Number of working environments per Connector

A Connector can manage multiple working environments in BlueXP. The maximum number of working environments that a single Connector should manage varies. It depends on the type of working environments, the number of volumes, the amount of capacity being managed, and the number of users.

If you have a large-scale deployment, work with your NetApp representative to size your environment. If you experience any issues along the way, reach out to us by using the in-product chat.

== When to use multiple Connectors

In some cases, you might only need one Connector, but you might find yourself needing two or more Connectors.

Here are a few examples:

* You're using a multi-cloud environment (AWS and Azure), so you have one Connector in AWS and another in Azure. Each manages the Cloud Volumes ONTAP systems running in those environments.

* A service provider might use one NetApp account to provide services for their customers, while using another account to provide disaster recovery for one of their business units. Each account would have separate Connectors.

== Using multiple Connectors with the same working environment

You can manage a working environment with multiple Connectors at the same time for disaster recovery purposes. If one Connector goes down, you can switch to the other Connector to immediately manage the working environment.

To set up this configuration:

. link:task-managing-connectors.html[Switch to another Connector]
. Discover the existing working environment.
+
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-adding-systems.html[Add existing Cloud Volumes ONTAP systems to BlueXP^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html[Discover ONTAP clusters^]
. Set the https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-storage-management.html[Capacity Management Mode^]
+
Only the main Connector should be set to *Automatic Mode*. If you switch to another Connector for DR purposes, then you can change the Capacity Management Mode as needed.

== When to switch between Connectors

When you create your first Connector, BlueXP automatically uses that Connector for each additional working environment that you create. Once you create an additional Connector, you'll need to switch between them to see the working environments that are specific to each Connector.

link:task-managing-connectors.html[Learn how to switch between Connectors].

== The local user interface

While you should perform almost all tasks from the https://console.bluexp.netapp.com[SaaS user interface^], a local user interface is still available on the Connector. This interface is needed if you install the Connector in an environment that doesn't have internet access (like a Government region), and for a few tasks that need to be performed from the Connector itself, instead of the SaaS interface:

* link:task-configuring-proxy.html[Setting a proxy server]
* Installing a patch (you'll typically work with NetApp personnel to install a patch)
* Downloading AutoSupport messages (usually directed by NetApp personnel when you have issues)

link:task-managing-connectors.html#access-the-local-ui[Learn how to access the local UI].
