---
sidebar: sidebar
permalink: concept-overview.html
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers
summary: BlueXP enables IT experts and cloud architects to centrally manage their hybrid multi-cloud infrastructure using NetApp's cloud solutions.
---

= Learn about BlueXP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP enables IT experts and cloud architects to centrally manage their hybrid multi-cloud infrastructure using NetApp's cloud solutions.

== Features

BlueXP is an enterprise-class, SaaS-based management platform that keeps you in control of your data no matter where it is.

* Set up and use https://cloud.netapp.com/ontap-cloud[Cloud Volumes ONTAP^] for efficient, multi-protocol data management across clouds.
* Set up and use cloud file-storage services:
+
** https://bluexp.netapp.com/azure-netapp-files[Azure NetApp Files^]
** https://bluexp.netapp.com/fsx-for-ontap[Amazon FSx for ONTAP^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp[Cloud Volumes Service for Google Cloud^]
* Discover and manage https://bluexp.netapp.com/netapp-on-premises[on-premises storage^]
** E-Series systems
** ONTAP clusters
** StorageGRID systems
* Use BlueXP's services for data mobility, data protection, and data analysis and control:
** https://bluexp.netapp.com/cloud-backup[Cloud Backup^]
** https://bluexp.netapp.com/netapp-cloud-data-sense[Cloud Data Sense^]
** https://bluexp.netapp.com/cloud-sync-service[Cloud Sync^]
** https://bluexp.netapp.com/cloud-tiering[Cloud Tiering^]
** https://bluexp.netapp.com/digital-advisor[Digital Advisor^]
** https://bluexp.netapp.com/global-file-cache[Global File Cache^]
** https://bluexp.netapp.com/k8s[Kubernetes^]
** https://bluexp.netapp.com/ransomware-protection[Ransomware Protection^]
** https://bluexp.netapp.com/replication[Replication^]

https://cloud.netapp.com/cloud-manager[Learn more about BlueXP^]

== Supported cloud providers

BlueXP enables you to manage cloud storage and use cloud services in Amazon Web Services, Microsoft Azure, and Google Cloud.

== Cost

Pricing for BlueXP depends on the services that you plan to use. https://bluexp.netapp.com/pricing[Learn about BlueXP pricing^]

== How BlueXP works

BlueXP includes a SaaS-based interface that is integrated with the BlueXP website and Connectors that manage Cloud Volumes ONTAP and other cloud services.

=== Software-as-a-service

BlueXP is accessible through a https://console.bluexp.netapp.com[SaaS-based user interface^] and APIs. This SaaS experience enables you to automatically access the latest features as they're released and to easily switch between your BlueXP accounts and Connectors.

=== BlueXP account

When you log in to BlueXP for the first time, you're prompted to create a _BlueXP account_. This account provides multi-tenancy and enables you to organize users and resources in isolated _workspaces_.

link:concept-netapp-accounts.html[Learn more about accounts].

=== Connectors

You don't need a Connector to get started with BlueXP, but you'll need to create a Connector to unlock all BlueXP features and services. A Connector enables the management of resources and processes across your on-premises and cloud environments. It's required to use Cloud Volumes ONTAP and other data services.

link:concept-connectors.html[Learn more about Connectors].

=== Restricted and private sites

BlueXP is also supported in environments where you need to restrict some or all internet access. In those environments, you access the BlueXP interface and API through the Connector software, rather than through the SaaS website.

link:concept-modes.html[Learn about BlueXP deployment modes].

== SOC 2 Type 2 certification

An independent certified public accountant firm and services auditor examined BlueXP, Cloud Sync, Cloud Tiering, Cloud Data Sense, and Cloud Backup (BlueXP platform), and affirmed that they have achieved SOC 2 Type 2 reports based on the applicable Trust Services criteria.

https://www.netapp.com/company/trust-center/compliance/soc-2/[View NetApp's SOC 2 reports^]
