---
sidebar: sidebar
permalink: reference-permissions.html
keywords: permissions, actions
summary: In order to use the features and services in Cloud Manager, you'll need to provide permissions so that Cloud Manager can perform operations in your cloud environment. Use the links on this page to quickly access the permissions that are required in Cloud Manager.
---

= Permissions required for Cloud Manager
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
In order to use the features and services in Cloud Manager, you'll need to provide permissions so that Cloud Manager can perform operations in your cloud environment. Use the links on this page to quickly access the permissions that you need based on your goal.

== AWS permissions

=== Connector deployment

The user who creates a Connector from Cloud Manager needs specific permissions to deploy the instance in AWS.

link:task-creating-connectors-aws.html[View the step-by-step instructions where the permissions are listed].

=== Connector operation

The Connector requires specific permissions for day-to-day operations in AWS.

When Cloud Manager launches the Connector instance in AWS, it attaches a policy to the instance that provides the Connector with permissions to manage resources and processes within that AWS account. link:reference-permissions-aws.html[View AWS permissions for the Connector].

There are a few cases where you might need to create this IAM policy yourself:

* You're creating a Connector directly from the AWS Marketplace
+
link:task-launching-aws-mktp.html[Learn how to create a Connector from the AWS Marketplace].

* You're adding an additional set of AWS credentials to a Connector
+
link:task-adding-aws-accounts.html#add-credentials-to-a-connector[Learn how to add credentials to a Connector].

link:concept-accounts-aws.html[Learn more about AWS credentials and permissions].

=== Cloud Volumes ONTAP operation

An IAM role with the required permissions must be attached to each Cloud Volumes ONTAP node in AWS. The same is true for the HA mediator. It's easiest to let Cloud Manager create the IAM roles for you, but you can use your own roles. Using your own IAM role is required in the AWS Commercial Cloud Services Environment.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-set-up-iam-roles.html[Learn how to set up IAM roles yourself^]

== Azure permissions

=== Connector deployment

When you deploy a Connector from Cloud Manager, you need to use an Azure account or service principal that has permissions to deploy the Connector virtual machine in Azure.

link:task-creating-connectors-azure.html[View the step-by-step instructions where the permissions are listed].

=== Connector operation

The Connector requires specific permissions for day-to-day operations in Azure.

When Cloud Manager deploys the Connector virtual machine in Azure, it creates a custom role that provides Cloud Manager with permissions to manage resources and processes within that Azure subscription. link:reference-permissions-azure.html[View Azure permissions for the Connector].

There are a few cases where you might need to create this custome role yourself:

* You're creating a Connector directly from the Azure Marketplace
+
link:task-launching-azure-mktp.html[Learn how to create a Connector from the Azure Marketplace].

* You're adding an additional set of Azure credentials to a Connector
+
link:https://review.docs.netapp.com/us-en/cloud-manager-setup-admin_july-2022-aws-permissions/task-adding-azure-accounts.html#adding-additional-azure-credentials-to-cloud-manager[Learn how to add credentials to a Connector].

link:concept-accounts-azure.html[Learn more about Azure credentials and permissions].

== Google Cloud permissions

=== Connector deployment

The Google Cloud user who deploys a Connector from Cloud Manager needs specific permissions to deploy the Connector in Google Cloud.

link:task-creating-connectors-gcp.html[View the step-by-step instructions where the permissions are listed].

=== Connector operation

The service account for the Connector VM instance must have specific permissions for day-to-day operations. You need to associate the service account with the Connector when you deploy it from Cloud Manager.

link:task-creating-connectors-gcp.html[View the step-by-step instructions where the permissions are listed].

link:concept-accounts-gcp.html[Learn more about Google Cloud credentials and permissions].
