---
sidebar: sidebar
permalink: reference-checklist-restricted-mode.html
keywords: networking overview, networking requirements, endpoints, urls, get started, getting started, deployment
summary: Use this checklist to understand what's needed to get up and running with BlueXP in a typical deployment where the Connector has outbound internet access.
---

= Getting started overview for restricted mode
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should understand what's needed to get up and running with BlueXP in restricted mode so that you can prepare your environment.

The information that follows provides a high-level summary of what's required with links to pages that provide step-by-step details.

== A Connector

A Connector enables BlueXP to manage resources and processes within your public cloud environment. When you use BlueXP in restricted mode, you need to use the BlueXP user interface that's running on the Connector. You can't access BlueXP from the SaaS website.

Before you deploy a Connector, you'll need to set up permissions and networking.

=== Cloud provider permissions

You need an account that has permissions to deploy the Connector in your cloud provider.

NOTE: There are alternate ways to create a Connector: you can create a Connector from the link:task-launching-aws-mktp.html[AWS Marketplace], the link:task-launching-azure-mktp.html[Azure Marketplace], or you can link:task-installing-linux.html[manually install the software].

[cols="15,55,30",options="header"]
|===
| Location
| High-level steps
| Detailed steps

| AWS
a|
. Use a JSON file that includes the required permissions to create an IAM policy in AWS.
. Attach the policy to an IAM role or IAM user.
. When you create the Connector, provide BlueXP with the ARN of the IAM role or the AWS access key and secret key for the IAM user.
| link:task-creating-connectors-aws.html[Click here to view detailed steps].

| Azure
a|
. Use a JSON file that includes the required permissions to create a custom role in Azure.
. Assign the role to the user who will create the Connector from BlueXP.
. When you create the Connector, log in with the Microsoft account that has the required permissions (the login prompt that is owned and hosted by Microsoft).
| link:task-creating-connectors-azure.html[Click here to view detailed steps].

| Google Cloud
a|
. Use a YAML file that includes the required permissions to create a custom role in Google Cloud.
. Attach that role to the user who will create the Connector from BlueXP.
. If you plan to use Cloud Volumes ONTAP, set up a service account that has the required permissions.
. Enable Google Cloud APIs.
. When you create the Connector, log in with the Google account that has the required permissions (the login prompt is owned and hosted by Google).
| link:task-creating-connectors-gcp.html[Click here to view detailed steps].

|===

=== Networking

The network location where you deploy the Connector must have an outbound internet connection. The Connector requires outbound internet access to contact the following endpoints in order to manage resources and processes within your public cloud environment.

==== Outbound connections

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

| 
\https://<region>.amazonaws.com

| To manage resources in AWS.

| 
\https://management.azure.com
\https://login.microsoftonline.com

| To manage resources in Azure public regions.

| 
\https://management.usgovcloudapi.net
\https://login.microsoftonline.us

| To manage resources in Azure Government regions.

| 
\https://management.azure.microsoft.scloud
\https://login.microsoftonline.microsoft.scloud

| To manage resources in the Azure IL6 region.

| 
\https://management.chinacloudapi.cn
\https://login.chinacloudapi.cn

| To manage resources in Azure China regions.

| 
\https://www.googleapis.com/compute/v1/
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects

| To manage resources in Google Cloud.

| \https://support.netapp.com | To obtain licensing information and to send AutoSupport messages to NetApp support.

a| 

\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

a| To provide SaaS features and services within BlueXP.

NOTE: The Connector is currently contacting "cloudmanager.cloud.netapp.com" but it will start contacting "api.bluexp.netapp.com" in an upcoming release.

| \https://cloudmanagerinfraprod.azurecr.io

\https://*.blob.core.windows.net
| To upgrade the Connector and its Docker components.

|===

If you choose to manually install the Connector on your own Linux host (and not do so directly from the BlueXP interface), the installer for the Connector requires access to several endpoints during the installation process.

link:task-installing-linux.html[Review the list of endpoints].

==== Ports

There's no incoming traffic to the Connector, unless you initiate it.

HTTP (80) and HTTPS (443) provide access to the local UI, which you'll use in rare circumstances. SSH (22) is only needed if you need to connect to the host for troubleshooting. Meanwhile, inbound connections over port 3128 are required if you deploy Cloud Volumes ONTAP systems in a subnet where an outbound internet connection isn't available.

== A log in

Before you can log in to BlueXP, you need to sign up using your NetApp Support Site credentials or you can create a NetApp cloud login using your email and a password. After you log in, you can set up a federated connection.

== Network access from your web browser

In restricted mode, the BlueXP user interface is accessible from the Connector, which is software that you deploy in the cloud. As you use the BlueXP user interface, it contacts several endpoints to complete data management tasks. The machine running the web browser must have connections to the following endpoints.

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

| \https://signin.b2c.netapp.com
| Required to update NetApp Support Site (NSS) credentials or to add new NSS credentials to BlueXP.

|
\https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com
| Your web browser connects to these endpoints for centralized user authentication through BlueXP.

| \https://widget.intercom.io
| For in-product chat that enables you to talk to NetApp cloud experts.

|===

== What's next?

Now that you have an understanding of what's required to get up and running with BlueXP, the first step is to sign up and create an account.