---
sidebar: sidebar
permalink: reference-checklist-private-mode.html
keywords: networking overview, networking requirements, endpoints, urls, get started, getting started, deployment
summary: Use this checklist to understand what's needed to get up and running with BlueXP in a typical deployment where the Connector has outbound internet access.
---

= Prepare for private mode deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Look at the pre-flight for the Connector in the UI


You should understand what's needed to get up and running with BlueXP in private mode so that you can prepare your environment.

You'll need to ensure that you have the following:

. A dedicated Linux host for the Connector software.
+
<link:task-install-connector-onprem-no-internet.html#set-up-your-host[View Linux host requirements]>

. Permissions to deploy and manage Cloud Volumes ONTAP.
+
<too much detail to include the info here? it would be nice to send a single page to the cloud permissions guy... then when you go into BlueXP you just need to add the credentials... except for Google Cloud>

Include an image that shows your environment when you're done?

Need to say somewhere that the Connector must be installed in Google Cloud if you plan to create Cloud Volumes ONTAP

== Overview



== Permissions

== Networking



The information that follows provides a high-level summary of what's required with links to pages that provide step-by-step details.

== A Connector

A Connector enables BlueXP to manage resources and processes within your public cloud environment. When you use BlueXP in private mode, you need to use the BlueXP user interface that's running on the Connector. You can't access BlueXP from the SaaS website.

Before you deploy a Connector, you'll need to set up permissions and networking.

=== Cloud provider permissions

You need an account that has permissions to deploy the Connector in your cloud provider.

NOTE: There are alternate ways to create a Connector: you can create a Connector from the link:task-launching-aws-mktp.html[AWS Marketplace], the link:task-launching-azure-mktp.html[Azure Marketplace], or you can link:task-installing-linux.html[manually install the software].

[cols="15,55,30",options="header"]
|===
| Location
| High-level steps
| Detailed steps

| AWS
a|
. Use a JSON file that includes the required permissions to create an IAM policy in AWS.
. Attach the policy to an IAM role or IAM user.
. When you create the Connector, provide BlueXP with the ARN of the IAM role or the AWS access key and secret key for the IAM user.
| link:task-creating-connectors-aws.html[Click here to view detailed steps].

| Azure
a|
. Use a JSON file that includes the required permissions to create a custom role in Azure.
. Assign the role to the user who will create the Connector from BlueXP.
. When you create the Connector, log in with the Microsoft account that has the required permissions (the login prompt that is owned and hosted by Microsoft).
| link:task-creating-connectors-azure.html[Click here to view detailed steps].

| Google Cloud
a|
. Use a YAML file that includes the required permissions to create a custom role in Google Cloud.
. Attach that role to the user who will create the Connector from BlueXP.
. If you plan to use Cloud Volumes ONTAP, set up a service account that has the required permissions.
. Enable Google Cloud APIs.
. When you create the Connector, log in with the Google account that has the required permissions (the login prompt is owned and hosted by Google).
| link:task-creating-connectors-gcp.html[Click here to view detailed steps].

|===

==== Outbound connections



==== Ports

There's no incoming traffic to the Connector, unless you initiate it.

HTTP (80) and HTTPS (443) provide access to the local UI. SSH (22) is only needed if you need to connect to the host for troubleshooting.

== A log in

Before you can log in to BlueXP, you need to sign up using your NetApp Support Site credentials or you can create a NetApp cloud login using your email and a password. After you log in, you can set up a federated connection.

== What's next?

Now that you have an understanding of what's required to get up and running with BlueXP, the first step is to create a Connector.