---
sidebar: sidebar
permalink: reference-permissions-azure.html
keywords: permissions, azure, azure permissions
summary: When Cloud Manager launches the Connector VM in Azure, it attaches a custom role to the VM that provides the Connector with permissions to manage resources and processes within that Azure subscription. The Connector uses the permissions to make API calls to several Azure services.
---

= Azure permissions for the Connector
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When Cloud Manager launches the Connector VM in Azure, it attaches a custom role to the VM that provides the Connector with permissions to manage resources and processes within that Azure subscription. The Connector uses the permissions to make API calls to several Azure services.

== Custom role permissions

The custom role shown below provides the permissions that a Connector needs to manage resources and processes within your Azure network.

When you create a Connector directly from Cloud Manager, Cloud Manager automatically applies this custom role to the Connector.

If you deploy the Connector from the Azure Marketplace or if you manually install the Connector on a Linux host, then you'll need to set up the custom role yourself.

You also need to ensure that the role is up to date as new permissions are added in subsequent releases.

[source,json]
{
    "Name": "Cloud Manager Operator",
    "Actions": [
       "Microsoft.Compute/disks/delete",
                        "Microsoft.Compute/disks/read",
                        "Microsoft.Compute/disks/write",
                        "Microsoft.Compute/locations/operations/read",
                        "Microsoft.Compute/locations/vmSizes/read",
                        "Microsoft.Resources/subscriptions/locations/read",
                        "Microsoft.Compute/operations/read",
                        "Microsoft.Compute/virtualMachines/instanceView/read",
                        "Microsoft.Compute/virtualMachines/powerOff/action",
                        "Microsoft.Compute/virtualMachines/read",
                        "Microsoft.Compute/virtualMachines/restart/action",
                        "Microsoft.Compute/virtualMachines/deallocate/action",
                        "Microsoft.Compute/virtualMachines/start/action",
                        "Microsoft.Compute/virtualMachines/vmSizes/read",
                        "Microsoft.Compute/virtualMachines/write",
                        "Microsoft.Compute/images/write",
                        "Microsoft.Compute/images/read",
                        "Microsoft.Network/locations/operationResults/read",
                        "Microsoft.Network/locations/operations/read",
                        "Microsoft.Network/networkInterfaces/read",
                        "Microsoft.Network/networkInterfaces/write",
                        "Microsoft.Network/networkInterfaces/join/action",
                        "Microsoft.Network/networkSecurityGroups/read",
                        "Microsoft.Network/networkSecurityGroups/write",
                        "Microsoft.Network/networkSecurityGroups/join/action",
                        "Microsoft.Network/virtualNetworks/read",
                        "Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read",
                        "Microsoft.Network/virtualNetworks/subnets/read",
                        "Microsoft.Network/virtualNetworks/subnets/write",
                        "Microsoft.Network/virtualNetworks/subnets/virtualMachines/read",
                        "Microsoft.Network/virtualNetworks/virtualMachines/read",
                        "Microsoft.Network/virtualNetworks/subnets/join/action",
                        "Microsoft.Resources/deployments/operations/read",
                        "Microsoft.Resources/deployments/read",
                        "Microsoft.Resources/deployments/write",
                        "Microsoft.Resources/resources/read",
                        "Microsoft.Resources/subscriptions/operationresults/read",
                        "Microsoft.Resources/subscriptions/resourceGroups/delete",
                        "Microsoft.Resources/subscriptions/resourceGroups/read",
                        "Microsoft.Resources/subscriptions/resourcegroups/resources/read",
                        "Microsoft.Resources/subscriptions/resourceGroups/write",
                        "Microsoft.Storage/checknameavailability/read",
                        "Microsoft.Storage/operations/read",
                        "Microsoft.Storage/storageAccounts/listkeys/action",
                        "Microsoft.Storage/storageAccounts/read",
                        "Microsoft.Storage/storageAccounts/delete",
                        "Microsoft.Storage/storageAccounts/regeneratekey/action",
                        "Microsoft.Storage/storageAccounts/write",
                        "Microsoft.Storage/storageAccounts/blobServices/containers/read",
                        "Microsoft.Storage/usages/read",
                        "Microsoft.Compute/snapshots/write",
                        "Microsoft.Compute/snapshots/read",
                        "Microsoft.Compute/availabilitySets/write",
                        "Microsoft.Compute/availabilitySets/read",
                        "Microsoft.Compute/disks/beginGetAccess/action",
                        "Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/read",
                        "Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/write",
                        "Microsoft.Network/loadBalancers/read",
                        "Microsoft.Network/loadBalancers/write",
                        "Microsoft.Network/loadBalancers/delete",
                        "Microsoft.Network/loadBalancers/backendAddressPools/read",
                        "Microsoft.Network/loadBalancers/backendAddressPools/join/action",
                        "Microsoft.Network/loadBalancers/frontendIPConfigurations/read",
                        "Microsoft.Network/loadBalancers/loadBalancingRules/read",
                        "Microsoft.Network/loadBalancers/probes/read",
                        "Microsoft.Network/loadBalancers/probes/join/action",
                        "Microsoft.Authorization/locks/*",
                        "Microsoft.Network/routeTables/join/action",
                        "Microsoft.NetApp/netAppAccounts/read",
                        "Microsoft.NetApp/netAppAccounts/capacityPools/read",
                        "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write",
                        "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read",
                        "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete",
                        "Microsoft.Network/privateEndpoints/write",
                        "Microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval/action",
                        "Microsoft.Storage/storageAccounts/privateEndpointConnections/read",
                        "Microsoft.Storage/storageAccounts/managementPolicies/read",
                        "Microsoft.Storage/storageAccounts/managementPolicies/write",
                        "Microsoft.Network/privateEndpoints/read",
                        "Microsoft.Network/privateDnsZones/write",
                        "Microsoft.Network/privateDnsZones/virtualNetworkLinks/write",
                        "Microsoft.Network/virtualNetworks/join/action",
                        "Microsoft.Network/privateDnsZones/A/write",
                        "Microsoft.Network/privateDnsZones/read",
                        "Microsoft.Network/privateDnsZones/virtualNetworkLinks/read",
                        "Microsoft.Resources/deployments/operationStatuses/read",
                        "Microsoft.Insights/Metrics/Read",
                        "Microsoft.Compute/virtualMachines/extensions/write",
                        "Microsoft.Compute/virtualMachines/extensions/delete",
                        "Microsoft.Compute/virtualMachines/extensions/read",
                        "Microsoft.Compute/virtualMachines/delete",
                        "Microsoft.Network/networkInterfaces/delete",
                        "Microsoft.Network/networkSecurityGroups/delete",
                        "Microsoft.Resources/deployments/delete",
                        "Microsoft.Compute/diskEncryptionSets/read",
                        "Microsoft.Compute/snapshots/delete",
                        "Microsoft.Network/privateEndpoints/delete",
                        "Microsoft.Compute/availabilitySets/delete",
                        "Microsoft.KeyVault/vaults/read",
                        "Microsoft.KeyVault/vaults/accessPolicies/write",
                        "Microsoft.Compute/diskEncryptionSets/write",
                        "Microsoft.KeyVault/vaults/deploy/action",
                        "Microsoft.Compute/diskEncryptionSets/delete",
                        "Microsoft.Resources/tags/read",
                        "Microsoft.Resources/tags/write",
                        "Microsoft.Resources/tags/delete",
                        "Microsoft.Network/applicationSecurityGroups/write",
                        "Microsoft.Network/applicationSecurityGroups/read",
                        "Microsoft.Network/applicationSecurityGroups/joinIpConfiguration/action",
                        "Microsoft.Network/networkSecurityGroups/securityRules/write",
                        "Microsoft.Network/applicationSecurityGroups/delete",
                        "Microsoft.Network/networkSecurityGroups/securityRules/delete",
                        "Microsoft.Network/publicIPAddresses/delete",
                        "Microsoft.Storage/storageAccounts/blobServices/containers/write",
                        "Microsoft.ContainerService/managedClusters/read",
                        "Microsoft.ContainerService/managedClusters/listClusterUserCredential/action"
    ],
    "NotActions": [],
    "AssignableScopes": [],
    "Description": "Cloud Manager Permissions",
    "IsCustom": "true"
}

== How Azure permissions are used

The following sections describe how the permissions are used for each NetApp cloud service. This information can be helpful if your corporate policies dictate that permissions are only provided as needed.

=== AppTemplate tags

The Connector makes the following API requests to manage tags on Azure resources when you use the AppTemplate Tagging service:

//tag::app-template-permissions[]
* Microsoft.Resources/resources/read",
"Microsoft.Resources/subscriptions/operationresults/read",
"Microsoft.Resources/subscriptions/resourceGroups/read",
"Microsoft.Resources/subscriptions/resourcegroups/resources/read",
"Microsoft.Resources/tags/read",
"Microsoft.Resources/tags/write",
//end::app-template-permissions[]

=== Cloud Backup

The Connector makes the following API requests to deploy the restore instance for Cloud Backup:

//tag::backup-permissions-restore[]
"Microsoft.Compute/virtualMachines/read",
"Microsoft.Compute/virtualMachines/start/action",
"Microsoft.Compute/virtualMachines/deallocate/action",
"Microsoft.Storage/storageAccounts/listkeys/action",
"Microsoft.Storage/storageAccounts/read",
"Microsoft.Storage/storageAccounts/write"
"Microsoft.Storage/storageAccounts/blobServices/containers/read",
"Microsoft.KeyVault/vaults/read",
"Microsoft.KeyVault/vaults/accessPolicies/write"
"Microsoft.Network/networkInterfaces/read",
"Microsoft.Resources/subscriptions/locations/read",
"Microsoft.Network/virtualNetworks/read",
"Microsoft.Network/virtualNetworks/subnets/read",
"Microsoft.Resources/deployments/read",
"Microsoft.Resources/deployments/write",
"Microsoft.Resources/subscriptions/operationresults/read",
"Microsoft.Resources/subscriptions/resourceGroups/read",
"Microsoft.Resources/subscriptions/resourcegroups/resources/read",
"Microsoft.Resources/subscriptions/resourceGroups/write",
"Microsoft.Authorization/locks/*",
"Microsoft.Network/privateEndpoints/write",
"Microsoft.Network/privateEndpoints/read",
"Microsoft.Network/privateDnsZones/virtualNetworkLinks/write",
"Microsoft.Network/virtualNetworks/join/action",
"Microsoft.Network/privateDnsZones/A/write",
"Microsoft.Network/privateDnsZones/read",
"Microsoft.Network/privateDnsZones/virtualNetworkLinks/read",
"Microsoft.Compute/virtualMachines/extensions/delete",
"Microsoft.Compute/virtualMachines/delete",
"Microsoft.Network/networkInterfaces/delete",
"Microsoft.Network/networkSecurityGroups/delete",
"Microsoft.Resources/deployments/delete",
"Microsoft.Resources/tags/read",
"Microsoft.Resources/tags/write",
"Microsoft.Network/publicIPAddresses/delete"
"Microsoft.Storage/storageAccounts/blobServices/containers/write"
//end::backup-permissions-restore[]

The Connector makes the following API requests to manage backups in Amazon S3:

//tag::backup-permissions[]
???
//end::backup-permissions[]

=== Cloud Data Sense

The Connector makes the following API requests to deploy the Cloud Data Sense instance:

//tag::data-sense-instance-permissions[]
"Microsoft.Compute/locations/operations/read",
"Microsoft.Compute/locations/vmSizes/read",
"Microsoft.Compute/operations/read",
"Microsoft.Compute/virtualMachines/instanceView/read",
"Microsoft.Compute/virtualMachines/powerOff/action",
"Microsoft.Compute/virtualMachines/read",
"Microsoft.Compute/virtualMachines/restart/action",
"Microsoft.Compute/virtualMachines/start/action",
"Microsoft.Compute/virtualMachines/write",
"Microsoft.Compute/images/read",
"Microsoft.Compute/disks/delete",
"Microsoft.Compute/disks/read",
"Microsoft.Compute/disks/write",
"Microsoft.Storage/checknameavailability/read",
"Microsoft.Storage/operations/read",
"Microsoft.Storage/storageAccounts/listkeys/action",
"Microsoft.Storage/storageAccounts/read",
"Microsoft.Storage/storageAccounts/write"
"Microsoft.Storage/storageAccounts/blobServices/containers/read",
"Microsoft.Network/networkInterfaces/read",
"Microsoft.Network/networkInterfaces/write",
"Microsoft.Network/networkInterfaces/join/action",
"Microsoft.Network/networkSecurityGroups/read",
"Microsoft.Network/networkSecurityGroups/write",
"Microsoft.Resources/subscriptions/locations/read",
"Microsoft.Network/locations/operationResults/read",
"Microsoft.Network/locations/operations/read",
"Microsoft.Network/virtualNetworks/read",
"Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read",
"Microsoft.Network/virtualNetworks/subnets/read",
"Microsoft.Network/virtualNetworks/subnets/virtualMachines/read",
"Microsoft.Network/virtualNetworks/virtualMachines/read",
"Microsoft.Network/virtualNetworks/subnets/join/action",
"Microsoft.Network/virtualNetworks/subnets/write",
"Microsoft.Network/routeTables/join/action",
"Microsoft.Resources/deployments/operations/read",
"Microsoft.Resources/deployments/read",
"Microsoft.Resources/deployments/write",
"Microsoft.Resources/resources/read",
"Microsoft.Resources/subscriptions/operationresults/read",
"Microsoft.Resources/subscriptions/resourceGroups/delete",
"Microsoft.Resources/subscriptions/resourceGroups/read",
"Microsoft.Resources/subscriptions/resourcegroups/resources/read",
"Microsoft.Resources/subscriptions/resourceGroups/write",
//end::data-sense-instance-permissions[]

The Connector makes the following API requests to scan Azure Blob storage when you use Cloud Data Sense:

//tag::data-sense-permissions[]
???
//end::data-sense-permissions[]

=== Cloud Tiering

The Connector makes the following API requests to tier data to Azure Blob storage when you use Cloud Tiering.

//tag::tiering-permissions[]
"Microsoft.Storage/storageAccounts/listkeys/action",
"Microsoft.Storage/storageAccounts/read",
"Microsoft.Storage/storageAccounts/write"
"Microsoft.Storage/storageAccounts/blobServices/containers/read",
"Microsoft.Resources/subscriptions/locations/read",
"Microsoft.Resources/subscriptions/operationresults/read",
"Microsoft.Resources/subscriptions/resourceGroups/read",
"Microsoft.Resources/subscriptions/resourceGroups/write",
"Microsoft.Storage/storageAccounts/managementPolicies/read"
"Microsoft.Storage/storageAccounts/managementPolicies/write"
"Microsoft.Storage/storageAccounts/blobServices/containers/write"
//end::tiering-permissions[]

=== Cloud Volumes ONTAP

The Connector makes the following API requests to deploy and manage Cloud Volumes ONTAP in AWS.

[cols=5*,options="header"]
|===

| Purpose
| Action
| Used for deployment?
| Used for daily operations?
| Used for deletion?

.11+| Create Cloud Volumes ONTAP and stop, start, delete, and obtain the status of the system.
"Microsoft.Compute/locations/operations/read", | Yes | Yes | No
"Microsoft.Compute/locations/vmSizes/read", | Yes | Yes | No
"Microsoft.Resources/subscriptions/locations/read", | Yes | No | No
"Microsoft.Compute/operations/read", | Yes | Yes | No
"Microsoft.Compute/virtualMachines/instanceView/read", | Yes | Yes | No
"Microsoft.Compute/virtualMachines/powerOff/action", | Yes | Yes | No
"Microsoft.Compute/virtualMachines/read", | Yes | Yes | No
"Microsoft.Compute/virtualMachines/restart/action", | Yes | Yes | No
"Microsoft.Compute/virtualMachines/start/action", | Yes | Yes | No
"Microsoft.Compute/virtualMachines/deallocate/action", | No | Yes | No
"Microsoft.Compute/virtualMachines/vmSizes/read", | No | Yes | No
"Microsoft.Compute/virtualMachines/write", | Yes | Yes | No

.2+| Enable Cloud Volumes ONTAP deployment from a VHD.
"Microsoft.Compute/images/write", | No | No | No
"Microsoft.Compute/images/read", | Yes | No | No

.3+| Create and manage network interfaces for Cloud Volumes ONTAP in the target subnet
"Microsoft.Network/networkInterfaces/read", | Yes | Yes | No
"Microsoft.Network/networkInterfaces/write", | Yes | Yes | No
"Microsoft.Network/networkInterfaces/join/action", | Yes | Yes | No

.3+| Create predefined network security groups for Cloud Volumes ONTAP
"Microsoft.Network/networkSecurityGroups/read", | Yes | Yes | No
"Microsoft.Network/networkSecurityGroups/write", | Yes | Yes | No
"Microsoft.Network/networkSecurityGroups/join/action", | ? | No | No

.9+| Get network information about regions, the target VNet and subnet, and add Cloud Volumes ONTAP to VNets
"Microsoft.Network/locations/operationResults/read", | Yes | Yes | No
"Microsoft.Network/locations/operations/read", | Yes | Yes | No
"Microsoft.Network/virtualNetworks/read", | Yes | No | No
"Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read", | Yes | No | No
"Microsoft.Network/virtualNetworks/subnets/read", | Yes | Yes | No
"Microsoft.Network/virtualNetworks/subnets/virtualMachines/read", | Yes | Yes | No
"Microsoft.Network/virtualNetworks/virtualMachines/read", | Yes | Yes | No
"Microsoft.Network/virtualNetworks/subnets/join/action", | Yes | Yes | No

.9+| Create and manage resource groups for Cloud Volumes ONTAP
"Microsoft.Resources/deployments/operations/read", | Yes | Yes | No
"Microsoft.Resources/deployments/read", | Yes | Yes | No
"Microsoft.Resources/deployments/write", | Yes | Yes | No
"Microsoft.Resources/resources/read", | Yes | Yes | No
"Microsoft.Resources/subscriptions/operationresults/read", | Yes | Yes | No
"Microsoft.Resources/subscriptions/resourceGroups/delete", | Yes | Yes | No
"Microsoft.Resources/subscriptions/resourceGroups/read", | No | Yes | No
"Microsoft.Resources/subscriptions/resourcegroups/resources/read", | Yes | Yes | No
"Microsoft.Resources/subscriptions/resourceGroups/write", | Yes | Yes | No

.11+| Manage Azure storage accounts and disks and attach the disks to Cloud Volumes ONTAP
"Microsoft.Compute/disks/read", | Yes | Yes | No
"Microsoft.Compute/disks/write", | Yes | Yes | No
"Microsoft.Compute/disks/delete", | Yes | Yes | No
"Microsoft.Storage/checknameavailability/read", | Yes | Yes | No
"Microsoft.Storage/operations/read", | Yes | Yes | No
"Microsoft.Storage/storageAccounts/listkeys/action", | Yes | Yes | No
"Microsoft.Storage/storageAccounts/read", | Yes | Yes | No
"Microsoft.Storage/storageAccounts/delete", | No | Yes | No
"Microsoft.Storage/storageAccounts/regeneratekey/action", | No | No | No
"Microsoft.Storage/storageAccounts/write" | Yes | Yes | No
"Microsoft.Storage/usages/read", | No | Yes | No

.3+| Enable backups to Azure Blob storage and encryption of storage accounts
"Microsoft.Storage/storageAccounts/blobServices/containers/read", | Yes | Yes | No
"Microsoft.KeyVault/vaults/read", | Yes | Yes | No
"Microsoft.KeyVault/vaults/accessPolicies/write" | Yes | Yes | No

.2+| Enable VNet service endpoints for data tiering
"Microsoft.Network/virtualNetworks/subnets/write", | Yes | Yes | No
"Microsoft.Network/routeTables/join/action", | Yes | Yes | No

.4+| Create and manage Azure managed snapshots
"Microsoft.Compute/snapshots/write", | Yes | Yes | No
"Microsoft.Compute/snapshots/read", | Yes | Yes | No
"Microsoft.Compute/snapshots/delete", | No | Yes | No
"Microsoft.Compute/disks/beginGetAccess/action", | No | Yes | No

.2+| Create and manage availability sets for Cloud Volumes ONTAP
"Microsoft.Compute/availabilitySets/write",
"Microsoft.Compute/availabilitySets/read",

.2+| Enable programmatic deployments from the Azure Marketplace.
"Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/read", | Yes | No | No
"Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/write", | Yes | Yes | No

.9+| Manage an Azure load balancer for HA pairs
"Microsoft.Network/loadBalancers/read", | Yes | Yes | No
"Microsoft.Network/loadBalancers/write", | Yes | No | No
"Microsoft.Network/loadBalancers/delete", | No | Yes | No
"Microsoft.Network/loadBalancers/backendAddressPools/read", | Yes | Yes | No
"Microsoft.Network/loadBalancers/backendAddressPools/join/action", | No | No | No
"Microsoft.Network/loadBalancers/frontendIPConfigurations/read", | No | No | No
"Microsoft.Network/loadBalancers/loadBalancingRules/read", | Yes | No | No
"Microsoft.Network/loadBalancers/probes/read", | Yes | No | No
"Microsoft.Network/loadBalancers/probes/join/action", | Yes | No | No

| Enable management of locks on Azure disks
| "Microsoft.Authorization/locks/*", | Yes | Yes | No

.10+| Enable the management of private endpoints when connectivity isn't provided to outside the subnet. Cloud Manager creates the storage account for HA with only internal connectivity within the subnet.
"Microsoft.Network/privateEndpoints/write", | Yes | Yes | No
"Microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval/action", | Yes | No | No
"Microsoft.Storage/storageAccounts/privateEndpointConnections/read", | Yes | Yes | No
"Microsoft.Network/privateEndpoints/read", | Yes | Yes | No
"Microsoft.Network/privateDnsZones/write", | Yes | Yes | No
"Microsoft.Network/privateDnsZones/virtualNetworkLinks/write", | Yes | Yes | No
"Microsoft.Network/virtualNetworks/join/action", | Yes | Yes | No
"Microsoft.Network/privateDnsZones/A/write", | Yes | Yes | No
"Microsoft.Network/privateDnsZones/read", | Yes | Yes | No
"Microsoft.Network/privateDnsZones/virtualNetworkLinks/read", | Yes | Yes | No

| Azure requires this permission for some virtual machine deployments (it depends on the underlying physical hardware that's used during deployment).
| "Microsoft.Resources/deployments/operationStatuses/read"  | Yes | Yes | No

| Enables you to use Global File Cache.
"Microsoft.Insights/Metrics/Read",
"Microsoft.Compute/virtualMachines/extensions/write",
"Microsoft.Compute/virtualMachines/extensions/read",
"Microsoft.Compute/virtualMachines/extensions/delete",
"Microsoft.Compute/virtualMachines/delete",
"Microsoft.Network/networkInterfaces/delete",
"Microsoft.Network/networkSecurityGroups/delete",
"Microsoft.Resources/deployments/delete",

.2+| Remove resources from a resource group that belongs to Cloud Volumes ONTAP in case of deployment failure or deletion
"Microsoft.Network/privateEndpoints/delete", | Yes | Yes | No
"Microsoft.Compute/availabilitySets/delete", | Yes | Yes | No

.4+| Enable the use of customer-managed encryption keys with Cloud Volumes ONTAP using the Cloud Manager API
"Microsoft.Compute/diskEncryptionSets/read" | Yes | Yes | No
"Microsoft.Compute/diskEncryptionSets/write", | Yes | Yes | No
"Microsoft.KeyVault/vaults/deploy/action", | Yes | No | No
"Microsoft.Compute/diskEncryptionSets/delete" | Yes | Yes | No

| Enables Cloud Manager to configure an application security group for an HA pair, which isolates the HA interconnect and cluster network NICs.
"Microsoft.Network/applicationSecurityGroups/write", | No | Yes | No
"Microsoft.Network/applicationSecurityGroups/read", | No | Yes | Yes
"Microsoft.Network/applicationSecurityGroups/joinIpConfiguration/action", | No | Yes | No
"Microsoft.Network/networkSecurityGroups/securityRules/write", | Yes | Yes | No
"Microsoft.Network/applicationSecurityGroups/delete", | No | Yes | No
"Microsoft.Network/networkSecurityGroups/securityRules/delete" | No | Yes | Yes




*** Listed in Excel but for CVO when I have them for the tagging service ***

Manage tags on your Azure resources using the Cloud Manager Tagging service.
"Microsoft.Resources/tags/read",
"Microsoft.Resources/tags/write",
"Microsoft.Resources/tags/delete"

*** Missing from Excel. I have them listed as for using customer-managed encryption keys***

"Microsoft.KeyVault/vaults/read",
"Microsoft.KeyVault/vaults/accessPolicies/write",

*** Used for ANF, but listed under CVO in the Excel file ***

"Microsoft.NetApp/netAppAccounts/read",
"Microsoft.NetApp/netAppAccounts/capacityPools/read",
"Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write",
"Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read",
"Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete",

*** Listed as No for deployment, operation, and deletion, but they're in the policy, so they must be used during some phase, right? ***

"Microsoft.Compute/images/write", | No | No | No
"Microsoft.Storage/storageAccounts/regeneratekey/action", | No | No | No
"Microsoft.Network/loadBalancers/backendAddressPools/join/action", | No | No | No
"Microsoft.Network/loadBalancers/frontendIPConfigurations/read", | No | No | No

*** Question mark listed under deployment ***

"Microsoft.Network/networkSecurityGroups/join/action",

*** Only two permissions listed as required for deletion. Is that correct? ***

|===

=== Kubernetes

The Connector makes the following API requests to discover and manage clusters running in Azure Kubernetes Service (AKS):

//tag::kubernetes-permissions[]
"Microsoft.Compute/virtualMachines/read",
"Microsoft.Resources/subscriptions/locations/read",
"Microsoft.Resources/subscriptions/operationresults/read",
"Microsoft.Resources/subscriptions/resourceGroups/read",
"Microsoft.Resources/subscriptions/resourcegroups/resources/read",
"Microsoft.ContainerService/managedClusters/read"
Microsoft.ContainerService/managedClusters/listClusterUserCredential/action
//end::kubernetes-permissions[]
