---
sidebar: sidebar
permalink: task-create-connectors-gov.html
keywords: government region, gov, govcloud, connector
summary: If you are operating in a Government region, you need to deploy a Connector from your cloud provider's marketplace or by using the manual installation method. You can't deploy the Connector in a Government region from Cloud Manager's SaaS website.
---

= Create a Connector in a Government region
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you are operating in a Government region, you need to deploy a Connector from your cloud provider's marketplace or by manually installing the Connector software on an existing Linux host. You can't deploy the Connector in a Government region from Cloud Manager's SaaS website.

* link:task-launching-aws-mktp.html#create-the-connector-in-an-aws-government-region[Create a Connector from the AWS Marketplace]
* link:task-launching-azure-mktp.html[Create a Connector from the Azure Marketplace]
* link:task-installing-linux.html[Install a Connector on your own Linux host]

After you deploy the Connector, you can access Cloud Manager by opening your web browser and connecting to the IP address of the Connector instance: http://_ipaddress_:80

Since the Connector was deployed in a Government region, it's not accessible from https://cloudmanager.netapp.com.
