---
sidebar: sidebar
permalink: task-set-up-permissions-aws.html
keywords: aws networking, networking, connector networking, ports, proxy server, outbound internet, endpoints, urls, permissions, cloud permission, aws permissions, iam role, keys, aws keys, aws marketplace, marketplace install, manuall install, connector installer
summary: Deploy a Connector in AWS so that BlueXP can manage resources and processes within your public cloud environment.
---

= Set up AWS permissions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Set up AWS permissions so that you can use BlueXP to manage your data and storage infrastructure. 

How you set up permissions depends on the installation option that you're planning to use.

* If you want to deploy the Connector directly from BlueXP, you'll need to set up permissions that enable BlueXP to authenticate with AWS and deploy the instance. BlueXP automatically sets up permissions for the Connector instance during deployment.

* If you intend to deploy the Connector from the AWS Marketplace or by manually installing the Connector, then you'll need to set up an IAM role that you can associate with the Connector instance.

== Set up permissions to create the Connector from BlueXP

BlueXP needs to authenticate with AWS before it can deploy the Connector instance in your VPC. You can choose one of these authentication methods:

* Let BlueXP assume an IAM role that has the required permissions
* Provide an AWS access key and secret key for an IAM user who has the required permissions

With either option, you first need to start by creating an IAM policy that includes the required permissions. This policy contains only the permissions needed to launch the Connector instance in AWS from BlueXP. Don't use this policy for other situations.

When BlueXP creates the Connector, it applies a new set of permissions to the Connector instance that enables the Connector to manage the resources in your public cloud environment.

.Steps

. Go to the AWS IAM console.

. Click *Policies > Create policy*.

. Click *JSON*.

. Copy and paste the following policy:
+
[source,json]
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "iam:PassRole",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DescribeImages",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "iam:GetRole",
                "iam:TagRole",
                "iam:ListRoles",
                "kms:ListAliases"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/OCCMInstance": "*"
                }
            },
            "Resource": [
                "arn:aws:ec2:*:*:instance/*"
            ]
        }
    ]
}

. Click *Next* and add tags, if needed.

. Click *Next* and enter a name and description.

. Click *Create policy*.

. Either attach the policy to an IAM role that BlueXP can assume or to an IAM user so that you can provide BlueXP with access keys:

* (Option 1) Set up an IAM role that BlueXP can assume:
+
.. Go to the AWS IAM console in the target account.

.. Under Access Management, click *Roles > Create Role* and follow the steps to create the role.

.. Under *Trusted entity type*, select *AWS account*.

.. Select *Another AWS account* and enter the ID of the BlueXP SaaS account: 952013314444

.. Select the policy that you created in the previous section.

.. After you create the role, copy the Role ARN so that you can paste it in BlueXP when you create the Connector.

* (Option 2) Set up permissions for an IAM user so that you can provide BlueXP with access keys:
+
.. From the AWS IAM console, click *Users* and then select the user name.

.. Click *Add permissions > Attach existing policies directly*.

.. Select the policy that you created.

.. Click *Next* and then click *Add permissions*.

.. Ensure that you have the access key and secret key for the IAM user.

.Result

You should now have an IAM role that has the required permissions or an IAM user that has the required permissions. When you create the Connector from BlueXP, you can provide information about the role or access keys.

== Set up permissions to create the Connector from the AWS Marketplace

Create IAM policies in AWS and attach them to an IAM role. When you create the Connector from the AWS Marketplace, you'll be prompted to select that IAM role.

.Steps

. From the IAM console, create a policy:

.. Click *Policies > Create policy*.

.. Select *JSON* and copy and paste the contents of the link:reference-permissions-aws.html[IAM policies for the Connector].

.. Finish the remaining steps to create the policy.
+
Depending on the BlueXP services that you're planning to use, you might need to create a second policy.
+
For standard regions, the permissions are spread across two policies. Two policies are required due to a maximum character size limit for managed policies in AWS. link:reference-permissions-aws.html[Learn more about IAM policies for the Connector].

. Back in the IAM console, create an IAM role:

.. Click *Roles > Create role*.

.. Select *AWS service > EC2*.

.. Add permissions by attaching the policies that you created in the previous step.

.. Finish the remaining steps to create the role.

.Result

You now have an IAM role that you can associate with the EC2 instance during deployment from the AWS Marketplace.

== Set up permissions to assign after manual installation

Create IAM policies in AWS and attach them to an IAM role.

If you manually install the Connector software on your own Linux host in AWS, you can provide permissions in the following ways:

* Option 1: Create IAM policies and an IAM role that you can associate with the EC2 instance.
* Option 2: Provide BlueXP with AWS access keys for an IAM user who has the required permissions.

// start tabbed area

[role="tabbed-block"]
====

.IAM role
--

.Steps

. From the IAM console, create a policy:

.. Click *Policies > Create policy*.

.. Select *JSON* and copy and paste the contents of the link:reference-permissions-aws.html[IAM policy for the Connector].

.. Finish the remaining steps to create the policy.
+
Depending on the BlueXP services that you're planning to use, you might need to create a second policy.
+
For standard regions, the permissions are spread across two policies. Two policies are required due to a maximum character size limit for managed policies in AWS. link:reference-permissions-aws.html[Learn more about IAM policies for the Connector].

. Back in the IAM console, create an IAM role:

.. Click *Roles > Create role*.

.. Select *AWS service > EC2*.

.. Add permissions by attaching the policies that you created in the previous step.

.. Finish the remaining steps to create the role.

.Result

You now have an IAM role that you can associate with the EC2 instance after you install the Connector.
--

.AWS access keys
--
.Steps

. From the IAM console, create a policy:

.. Click *Policies > Create policy*.

.. Select *JSON* and copy and paste the contents of the link:reference-permissions-aws.html[IAM policy for the Connector].

.. Finish the remaining steps to create the policy.
+
Depending on the BlueXP services that you're planning to use, you might need to create a second policy.
+
For standard regions, the permissions are spread across two policies. Two policies are required due to a maximum character size limit for managed policies in AWS. link:reference-permissions-aws.html[Learn more about IAM policies for the Connector].

. Attach the policies to an IAM user.
+
* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html[AWS Documentation: Creating IAM Roles^]
* https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html[AWS Documentation: Adding and Removing IAM Policies^]

. Ensure that the user has access keys that you can add to BlueXP after you install the Connector.

.Result

The account now has the required permissions. <<add-the-credentials,You can now add the credentials to a Connector>>.
--

====
// end tabbed area