---
sidebar: sidebar
permalink: task-set-up-networking-on-prem.html
keywords: aws networking, networking, connector networking, ports, proxy server, outbound internet, endpoints, urls, permissions, cloud permission, aws permissions, iam role, keys, aws keys, aws marketplace, marketplace install, manuall install, connector installer
summary: Deploy a Connector in AWS so that BlueXP can manage resources and processes within your public cloud environment.
---

= Set up on-prem networking
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Set up your networking so the Connector can manage resources and processes within your hybrid cloud environment.

== Connections to target networks

A Connector requires a network connection to the type of working environment that you're creating and the services that you're planning to enable.

For example, if you want to launch Cloud Volumes ONTAP in the cloud, then you must set up a VPN connection from your corporate network to the virtual network where you plan to launch Cloud Volumes ONTAP.

== Proxy server

If your organization requires deployment of a proxy server for all outgoing internet traffic, obtain the following information about your HTTP or HTTPS proxy:

* IP address
* Credentials
* HTTPS certificate

== Ports

There's no incoming traffic to the Connector, unless you initiate it or if the Connector is used as a proxy for AutoSupport messages.

* HTTP (80) and HTTPS (443) provide access to the https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#the-local-user-interface[local UI], which you'll use in rare circumstances. 

* SSH (22) is only needed if you need to connect to the host for troubleshooting. 

* Inbound connections over port 3128 are required if you deploy Cloud Volumes ONTAP systems in a subnet where an outbound internet connection isn't available.

== IP address limitation

There's a possible conflict with IP addresses in the 172 range. https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-limitations.html[Learn more about this limitation].

== Outbound internet access

The network location where you deploy the Connector must have an outbound internet connection.

=== Endpoints contacted during manual installation

When you manually install the Connector on your own Linux host, the installer for the Connector requires access to the following URLs during the installation process:

* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://cloudmanagerinfraprod.azurecr.io
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net

The host might try to update operating system packages during installation. The host can contact different mirroring sites for these OS packages.

=== Endpoints contacted for day-to-day operations

The Connector requires outbound internet access to contact the following endpoints in order to manage resources and processes within your public cloud environment.

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

| 
\https://<region>.amazonaws.com

| To manage resources in AWS.

| 
\https://management.azure.com
\https://login.microsoftonline.com

| To manage resources in Azure public regions.

| 
\https://management.usgovcloudapi.net
\https://login.microsoftonline.us

| To manage resources in Azure Government regions.

| 
\https://management.chinacloudapi.cn
\https://login.chinacloudapi.cn

| To manage resources in Azure China regions.

| 
\https://www.googleapis.com/compute/v1/
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects

| To manage resources in Google Cloud.

| \https://support.netapp.com | To obtain licensing information and to send AutoSupport messages to NetApp support.

a| 

\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

a| To provide SaaS features and services within BlueXP.

NOTE: The Connector is currently contacting "cloudmanager.cloud.netapp.com" but it will start contacting "api.bluexp.netapp.com" in an upcoming release.

| \https://cloudmanagerinfraprod.azurecr.io

\https://*.blob.core.windows.net
| To upgrade the Connector and its Docker components.

|===