---
sidebar: sidebar
permalink: task-create-account.html
keywords: create account, account, create, create another account, tenancy account, tenancy, tenancy account creation
summary: When you sign up to BlueXP, you're prompted to create an account for your organization. This account might be all that you need, but if your business requires multiple accounts, then you'll need to create additional accounts by using the Tenancy API. 
---

= Create another BlueXP account
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you sign up to BlueXP, you're prompted to create an account for your organization. This account might be all that you need, but if your business requires multiple accounts, then you'll need to create additional accounts by using the Tenancy API. 

Use the following API call to create an additional BlueXP account:

POST `/tenancy/account/{accountName}`

If you want to enable restricted mode, you need to include the following in the request body:

[source,JSON]
{
  "isSaasDisabled": true
}

NOTE: You can't change the restricted mode setting after BlueXP creates the account. You can't enable restricted mode later and you can't disable it later. It must be set at time of account creation.

https://docs.netapp.com/us-en/cloud-manager-automation/tenancy/post-tenancy-account-.html[Learn how to use this API call^]

.Related links

* link:concept-netapp-accounts.html[Learn about BlueXP accounts]
* link:concept-modes.html[Learn about BlueXP deployment modes]