---
sidebar: sidebar
permalink: task-logging-in-restricted-mode.html
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account
summary: When you use BlueXP in restricted mode, you'll need to log in to the BlueXP console from the user interface that runs locally on the Connector.
---

= Log in to BlueXP (restricted mode)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you use BlueXP in restricted mode, you'll need to log in to the BlueXP console from the user interface that runs locally on the Connector.

.Log in options

BlueXP supports logging in with one of the following options when your account is set up in restricted mode:

* A NetApp cloud login using your email address and a password
* A federated connection
+
A federated connection enables single sign-on using credentials from your corporate directory (federated identity). To learn more, go to the https://cloud.netapp.com/help-center[BlueXP Help Center^] and then click *sign-in options*.

.Steps

. Open a web browser and enter the following URL:
+
https://_ipaddress_
+
_ipaddress_ can be localhost, a private IP address, or a public IP address, depending on the configuration of the host where you installed the Connector. For example, you might need to enter a private IP address from a host that has a connection to the Connector host.

. Enter your user name and password to log in.

.Result

You're now logged in and can start using BlueXP to manage your hybrid multi-cloud infrastructure.