---
sidebar: sidebar
permalink: task-set-up-networking-aws.html
keywords: aws networking, networking, connector networking, ports, proxy server, outbound internet, endpoints, urls, vpc, subnet
summary: Set up your networking so the Connector can manage resources and processes within your hybrid cloud environment.
---

= Set up AWS networking
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Set up your networking so the Connector can manage resources and processes within your hybrid cloud environment. 

== VPC and subnet 

When you create the Connector, you need to specify the VPC and subnet where the Connector should reside.

== Connections to target networks

A Connector requires a network connection to the location where you're planning to create and manage working environments.

== Outbound internet access

The network location where you deploy the Connector must have an outbound internet connection.

=== Endpoints contacted during manual installation

If you plan to manually install the Connector on your own Linux host, the installer for the Connector requires access to the following URLs during the installation process:

* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://cloudmanagerinfraprod.azurecr.io
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net

The host might try to update operating system packages during installation. The host can contact different mirroring sites for these OS packages.

=== Endpoints contacted for day-to-day operations

The Connector requires outbound internet access to contact the following endpoints in order to manage resources and processes within your public cloud environment.

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

a|
AWS services (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Identity and Access Management (IAM)
* Key Management Service (KMS)
* Security Token Service (STS)
* Simple Storage Service (S3)

| To manage resources in AWS. The exact endpoint depends on the region in which you deploy the Connector. https://docs.aws.amazon.com/general/latest/gr/rande.html[Refer to AWS documentation for details^]

| \https://support.netapp.com | To obtain licensing information and to send AutoSupport messages to NetApp support.

a| 

\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

a| To provide SaaS features and services within BlueXP.

NOTE: The Connector is currently contacting "cloudmanager.cloud.netapp.com" but it will start contacting "api.bluexp.netapp.com" in an upcoming release.

| \https://cloudmanagerinfraprod.azurecr.io

\https://*.blob.core.windows.net
| To upgrade the Connector and its Docker components.

|===

.Related link

link:reference-networking-saas-console.html[Prepare networking for user access to the BlueXP console]

== Proxy server

If your organization requires deployment of a proxy server for all outgoing internet traffic, obtain the following information about your HTTP or HTTPS proxy:

* IP address
* Credentials
* HTTPS certificate

== Ports

There's no incoming traffic to the Connector, unless you initiate it or if the Connector is used as a proxy for AutoSupport messages.

* HTTP (80) and HTTPS (443) provide access to the local UI, which you'll use in rare circumstances. 

* SSH (22) is only needed if you need to connect to the host for troubleshooting. 

* Inbound connections over port 3128 are required if you deploy Cloud Volumes ONTAP systems in a subnet where an outbound internet connection isn't available.

== IP address limitation

There's a possible conflict with IP addresses in the 172 range. https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-limitations.html[Learn more about this limitation].