---
sidebar: sidebar
permalink: task-set-up-google-permissions-private.html
keywords: permissions, google cloud, google cloud permissions, gcp permissions, service account, role, private mode
summary: BlueXP requires permissions to deploy Cloud Volumes ONTAP in your Google Cloud projects. You'll need to set up a service account that has the required permissions and associate it with the Connector virtual machine.
---

= Provide Google Cloud permissions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP requires permissions to deploy Cloud Volumes ONTAP in your Google Cloud projects. You'll need to set up a service account that has the required permissions and associate it with the Connector virtual machine.

The contents of this page are specific to BlueXP when operating in private mode in the cloud. link:concept-modes.html[Learn more about supported deployment modes].

.Steps

. https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud[Create a role in Google Cloud^] that includes the permissions defined in the link:reference-permissions-gcp.html[Connector policy for GCP].

. https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account[Create a Google Cloud service account and apply the custom role that you just created^].

. https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes[Associate this service account with the Connector VM^].

. If you want to deploy Cloud Volumes ONTAP in other projects, https://cloud.google.com/iam/docs/granting-changing-revoking-access#granting-console[grant access by adding the service account with the BlueXP role to that project^]. You'll need to repeat this step for each project.

.Result

BlueXP can now use the credentials that are associated with the Connector virtual machine that's running in Google Cloud. BlueXP users can now use these credentials when creating a new Cloud Volumes ONTAP working environment.