---
sidebar: sidebar
permalink: task-set-up-permissions-private-mode-aws.html
keywords: networking overview, networking requirements, endpoints, urls, get started, getting started, deployment
summary: You should understand what's needed to get up and running with BlueXP in private mode so that you can prepare your environment.
---

= Set up AWS permissions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP requires permissions to manage resources and processes within your AWS account. How you provide the permissions depends on whether you want to provide BlueXP with the ARN of a role in a trusted account or AWS keys.

*Choices*

* <<Grant permissions by assuming an IAM role in another account>>
* <<Grant permissions by providing AWS keys>>

== Grant permissions by assuming an IAM role in another account

You can set up a trust relationship between the source AWS account in which you deployed the Connector instance and other AWS accounts by using IAM roles. You would then provide BlueXP with the ARN of the IAM roles from the trusted accounts.

.Steps

. Go to the IAM console in the target account in which you want to provide the Connector with permissions.

. Under Access Management, click *Roles > Create Role* and follow the steps to create the role.
+
Be sure to do the following:

* Under *Trusted entity type*, select *AWS account*.
* Select *Another AWS account* and enter the ID of the account where the Connector instance resides.
* Create the required policies by copying and pasting the contents of link:reference-permissions-aws.html[the IAM policies for the Connector].

. Copy the Role ARN of the IAM role so that you can paste it in BlueXP later on.

.Result

The account now has the required permissions. <<add-the-credentials,You can now add the credentials to a Connector>>.

== Grant permissions by providing AWS keys

If you want to provide BlueXP with AWS keys for an IAM user, then you need to grant the required permissions to that user. The BlueXP IAM policy defines the AWS actions and resources that BlueXP is allowed to use.

.Steps

. From the IAM console, create policies by copying and pasting the contents of link:reference-permissions-aws.html[the IAM policies for the Connector].
+
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html[AWS Documentation: Creating IAM Policies^]

. Attach the policies to an IAM role or an IAM user.
+
* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html[AWS Documentation: Creating IAM Roles^]
* https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html[AWS Documentation: Adding and Removing IAM Policies^]

.Result

The account now has the required permissions. <<add-the-credentials,You can now add the credentials to a Connector>>.