---
sidebar: sidebar
permalink: task-logging-in.html
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account
summary: After you sign up to BlueXP, you can log in from your web browser through the SaaS-based user interface.
---

= Log in to BlueXP (standard mode)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you sign up to BlueXP, you can log in from your web browser through the SaaS-based user interface. 

link:task-sign-up-saas.html[Learn how to sign up to BlueXP and create an organization].

.Log in options

You can log in to the BlueXP SaaS website using one of the following options:

* Your existing NetApp Support Site (NSS) credentials
* A NetApp cloud login using your email address and a password
* A federated connection
+
A federated connection enables single sign-on using credentials from your corporate directory (federated identity). To learn more, go to the https://cloud.netapp.com/help-center[BlueXP Help Center^] and then click *sign-in options*.

.Steps

. Open a web browser and go to the https://console.bluexp.netapp.com[BlueXP console^]

. On the *Log in* page, enter the email address that's associated with your login.

. Depending on the authentication method associated with your login, you'll be prompted to enter your credentials:
+
* NetApp cloud credentials: Enter your password
* Federated user: Enter your federated identity credentials
* NetApp Support Site account: Enter your NetApp Support Site credentials

.Result

You're now logged in and can start using BlueXP to manage your hybrid multi-cloud infrastructure.