---
sidebar: sidebar
permalink: task-prepare-connector-aws.html
keywords: networking overview, networking requirements, endpoints, urls, get started, getting started, deployment
summary: You should understand what's needed to get up and running with BlueXP in restricted mode so that you can prepare your environment. The preparation involves preparing a Linux host for the Connector, preparing your networking, and setting up cloud permissions.
---

= Prepare to create a Connector in AWS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should understand what's needed to get started with BlueXP in restricted mode so that you can prepare your environment.

== Understand your installation options

You can choose from the following options to create a Connector in AWS:

* Create the Connector directly from BlueXP (this is the )
* Create a Connector from the AWS Marketplace
* Download the installer and manually install the software on your own Linux host

The option that you choose impacts how you provide BlueXP with the required AWS permissions that it needs to authenticate and manage resources in AWS. 

== Review host requirements for manual installations

The Connector software must run on a host that meets specific operating system requirements, RAM requirements, port requirements, and so on. You should review this information when choosing a manual installation.

When you deploy the Connector from BlueXP or from the AWS Marketplace, the image includes the required OS and software components. 

Dedicated host::
The Connector is not supported on a host that is shared with other applications. The host must be a dedicated host.

Supported locations::
In restricted mode, you can only install the Connector in the cloud.

Supported operating systems::
* CentOS 7.6, 7.7, 7.8, and 7.9
* Red Hat Enterprise Linux 7.6, 7.7, 7.8, 7.9, and 8.6
+
The host must be registered with Red Hat Subscription Management. If it's not registered, the host can't access repositories to update required 3rd-party software during Connector installation.
+
The Connector is supported on English-language versions of these operating systems.

Hypervisor::
A bare metal or hosted hypervisor that is certified to run CentOS or Red Hat Enterprise Linux is required. https://access.redhat.com/certified-hypervisors[Red Hat Solution: Which hypervisors are certified to run Red Hat Enterprise Linux?^]

Networking::
<<Prepare networking for the Connector,Refer to the section below>>.

CPU:: 4 cores or 4 vCPUs

RAM:: 14 GB

AWS EC2 instance type::
An instance type that meets the CPU and RAM requirements above. We recommend t3.xlarge.

Azure VM size::
An instance type that meets the CPU and RAM requirements above. We recommend DS3 v2.

GCP machine type::
An instance type that meets the CPU and RAM requirements above. We recommend n2-standard-4.
+
The Connector is supported in Google Cloud on a VM instance with an OS that supports https://cloud.google.com/compute/shielded-vm/docs/shielded-vm[Shielded VM features^]

Disk space in /opt:: 100 GiB of space must be available

Disk space in /var:: 20 GiB of space must be available

Docker Engine:: Docker Engine version 19.3.1 or later is required on the host before you install the Connector. https://docs.docker.com/engine/install/[View installation instructions^]

== Prepare networking for the Connector

Set up your networking so the Connector can manage resources and processes within your public cloud environment. Other than having a virtual network and subnet for the Connector, you'll need to ensure that the following requirements are met.

=== Connection to target networks

A Connector requires a network connection to the type of working environment that you're creating and the services that you're planning to enable.

For example, if you install a Connector in your corporate network, then you must set up a VPN connection to the virtual network in which you launch Cloud Volumes ONTAP.

=== Proxy server

If your organization requires deployment of an HTTP proxy for all outgoing internet traffic, obtain the following information about your HTTP proxy:

* IP address
* Credentials
* HTTPS certificate

=== Security group

There's no incoming traffic to the Connector, unless you initiate it or if the Connector is used as a proxy for AutoSupport messages. HTTP and HTTPS provide access to the https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#the-local-user-interface[local UI], which you'll use in rare circumstances. SSH is only needed if you need to connect to the host for troubleshooting.

=== IP address limitation

There's a possible conflict with IP addresses in the 172 range. https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-limitations.html[Learn more about this limitation].

=== Outbound internet access for manual installs

If you plan to manually install the Connector on your own Linux host, the installer for the Connector requires access to the following URLs during the installation process:

* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://cloudmanagerinfraprod.azurecr.io
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net

The host might try to update operating system packages during installation. The host can contact different mirroring sites for these OS packages.

=== Outbound internet access for day-to-day operations

The network location where you deploy the Connector must have an outbound internet connection. The Connector requires outbound internet access to contact the following endpoints in order to manage resources and processes within your public cloud environment.

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

| 
\https://<region>.amazonaws.com

| To manage resources in AWS.

| \https://support.netapp.com | To obtain licensing information and to send AutoSupport messages to NetApp support.

a| 

\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

a| To provide SaaS features and services within BlueXP.

NOTE: The Connector is currently contacting "cloudmanager.cloud.netapp.com" but it will start contacting "api.bluexp.netapp.com" in an upcoming release.

| \https://cloudmanagerinfraprod.azurecr.io

\https://*.blob.core.windows.net
| To upgrade the Connector and its Docker components.

|===

== Prepare cloud permissions

BlueXP requires permissions from your cloud provider to deploy Cloud Volumes ONTAP in a virtual network and to use Cloud Backup and Cloud Data Sense. You need to set up permissions in your cloud provider and then associate those permission with the Connector instance after you install it.

The option that you choose impacts how you provide BlueXP with the required AWS permissions that it needs to authenticate and manage resources in AWS. 

// Start snippet: collapsible block (open on page load)
.Permissions for BlueXP deployment
[%collapsible]
====
BlueXP needs to authenticate with AWS before it can deploy the Connector instance in your VPC. You can choose one of these authentication methods:

* Let BlueXP assume an IAM role that has the required permissions
* Provide an AWS access key and secret key for an IAM user who has the required permissions

With either option, you first need to start by creating an IAM policy that includes the required permissions.

=== Create an IAM policy

This policy contains only the permissions needed to launch the Connector instance in AWS from BlueXP. Don't use this policy for other situations.

When BlueXP creates the Connector, it applies a new set of permissions to the Connector instance that enables the Connector to manage the resources in your public cloud environment.

.Steps

. Go to the AWS IAM console.

. Click *Policies > Create policy*.

. Click *JSON*.

. Copy and paste the following policy:
+
[source,json]
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "iam:PassRole",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DescribeImages",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "iam:GetRole",
                "iam:TagRole",
                "iam:ListRoles",
                "kms:ListAliases"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/OCCMInstance": "*"
                }
            },
            "Resource": [
                "arn:aws:ec2:*:*:instance/*"
            ]
        }
    ]
}

. Click *Next* and add tags, if needed.

. Click *Next* and enter a name and description.

. Click *Create policy*.

.What's next?

Either attach the policy to an IAM role that BlueXP can assume or to an IAM user.

=== Set up an IAM role

Set up an IAM role that BlueXP can assume in order to deploy the Connector in AWS.

.Steps

. Go to the AWS IAM console in the target account.

. Under Access Management, click *Roles > Create Role* and follow the steps to create the role.
+
Be sure to do the following:

* Under *Trusted entity type*, select *AWS account*.
* Select *Another AWS account* and enter the ID of the BlueXP SaaS account: 952013314444
* Select the policy that you created in the previous section.

. After you create the role, copy the Role ARN so that you can paste it in BlueXP when you create the Connector.

.Result

The IAM role now has the required permissions.

=== Set up permissions for an IAM user

When you create a Connector, you can provide an AWS access key and secret key for an IAM user who has the required permissions to deploy the Connector instance.

.Steps

. From the AWS IAM console, click *Users* and then select the user name.

. Click *Add permissions > Attach existing policies directly*.

. Select the policy that you created.

. Click *Next* and then click *Add permissions*.

. Ensure that you have access to an access key and secret key for the IAM user.

.Result

The AWS user now has the permissions required to create the Connector from BlueXP. You'll need to specify AWS access keys for this user when you're prompted by BlueXP.
====
// End snippet

// start tabbed area

// Start snippet: collapsible block (open on page load)
.Permissions for AWS Marketplace deployments
[%collapsible]
====
Create a policy and attach it to an IAM role.

.Steps

. From the IAM console, create your own policy by copying and pasting the contents of the link:reference-permissions-aws.html[IAM policy for the Connector].

. Create an IAM role with the role type Amazon EC2 and attach the policy that you created in the previous step to the role.

.Result

You now have an IAM role that you can associate with the EC2 instance after you deploy the Connector.
====
// End snippet

// Start snippet: collapsible block (open on page load)
.Permissions for manual installations
[%collapsible]
====
Create a policy and attach it to an IAM role.

.Steps

. From the IAM console, create your own policy by copying and pasting the contents of the link:reference-permissions-aws.html[IAM policy for the Connector].

. Create an IAM role with the role type Amazon EC2 and attach the policy that you created in the previous step to the role.

.Result

You now have an IAM role that you can associate with the EC2 instance after you deploy the Connector.
====
// End snippet