---
sidebar: sidebar
permalink: task-log-in-private-mode.html
keywords: logging in, log in, sign in, signing in, private mode, private mode log in, local log in, connector log in, log in connector
summary: When you use BlueXP in private mode, you'll need to log in to the BlueXP console from the user interface that runs locally on the Connector.
---

= Log in to BlueXP (private mode)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you use BlueXP in private mode, you'll need to log in to the BlueXP console from the user interface that runs locally on the Connector.

.Log in options

Private mode supports local user management and access. Authentication is not provided through BlueXP's cloud service.

.Steps

. Open a web browser and enter the following URL:
+
https://_ipaddress_
+
_ipaddress_ can be localhost, a private IP address, or a public IP address, depending on the configuration of the host where you installed the Connector. For example, you might need to enter a private IP address from a host that has a connection to the Connector host.

. Enter your user name and password to log in.

.Result

You're now logged in and can start using BlueXP to manage your hybrid multi-cloud infrastructure.