---
sidebar: sidebar
permalink: task-create-connectors-gov.html
keywords: government region, gov, govcloud, connector
summary: If you are operating in a Government region, you need to deploy a Connector from your cloud provider's marketplace or by using the manual installation method. You can't deploy the Connector in a Government region from Cloud Manager's SaaS website.
---

= Create a Connector in a Government region
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you are operating in a Government region, you need to deploy a Connector from your cloud provider's marketplace or by manually installing the Connector software on an existing Linux host. You can't deploy the Connector in a Government region from Cloud Manager's SaaS website.

Use one of the following links to view instructions for creating a Connector:

* link:task-launching-aws-mktp.html#create-the-connector-in-an-aws-government-region[Create a Connector from the AWS Marketplace]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws-c2s.html[Create a Connector and Cloud Volumes ONTAP in the AWS C2S environment^]
* link:task-launching-azure-mktp.html[Create a Connector from the Azure Marketplace]
* link:task-installing-linux.html[Install a Connector on your own Linux host]
+
For manual installations on your own Linux host, you must use the "online" installer to install the Connector on a host that has internet access. A separate "offline" installer is available for Cloud Manager, but it's only supported with on-prem sites that don't have internet access. It's not supported with Government regions.

After you deploy the Connector, you can access Cloud Manager by opening your web browser and connecting to the IP address of the Connector instance: http://_ipaddress_

Since the Connector was deployed in a Government region, it's not accessible from https://cloudmanager.netapp.com.
